"""How the system perceives and acts on an application surface."""

from cua.surface.base import (
    Action,
    ActionResult,
    Box,
    Capturable,
    DialogEvent,
    ElementInfo,
    FrameHop,
    FrameObservation,
    HarvestError,
    HumanAction,
    LocatingSurface,
    LocatorAttempt,
    LocatorNotFound,
    Observation,
    RequestGuard,
    RequestInfo,
    Resolved,
    StaleRefError,
    Surface,
    SurfaceError,
    SurfaceUnavailable,
    UnknownRefError,
    UnknownSecretError,
)
from cua.surface.playwright_surface import PlaywrightSurface, SurfaceConfig

__all__ = [
    "Action",
    "ActionResult",
    "Box",
    "Capturable",
    "DialogEvent",
    "ElementInfo",
    "FrameHop",
    "FrameObservation",
    "HarvestError",
    "HumanAction",
    "LocatingSurface",
    "LocatorAttempt",
    "LocatorNotFound",
    "Observation",
    "PlaywrightSurface",
    "RequestGuard",
    "RequestInfo",
    "Resolved",
    "StaleRefError",
    "Surface",
    "SurfaceConfig",
    "SurfaceError",
    "SurfaceUnavailable",
    "UnknownRefError",
    "UnknownSecretError",
]
